#pragma once

#include <iostream>
#include <cinttypes>
#include <cstdlib>
#include <limits>
#include <cstdint>
#include <cstddef>
#include <string>
#include <sstream>
#include <cstdbool>
#include <fstream>
#include <optional>
#include <functional>
#include <vector>
#include <array>
#include <map>
#include <filesystem>
#include <iterator>
#include <algorithm>
#include <chrono>
#include <deque>
#include <list>
#include <queue>
#include <stack>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <initializer_list>
#include <compare>
#include <type_traits>
#include <variant>
#include <concepts>
#include <any>
#include <memory>
#include <utility>
#include <thread>
#include <mutex>
#include <random>
#include <span>
#include <typeindex>
#include <new>
#include <bit>